insert into INTERNS values(nextval('PUBLIC', 'INTERNS_SEQUENCE'), 'Cristina Popescu', 'cristina.popescu@accesa.eu', '2004-12-31');
insert into INTERNS values(nextval('PUBLIC', 'INTERNS_SEQUENCE'), 'Andrei Tigan', 'andrei.tigan@accesa.eu', '2004-12-31');
insert into INTERNS values(nextval('PUBLIC', 'INTERNS_SEQUENCE'), 'Cristi (Dan) Flore', 'dan.flore@accesa.eu', '2004-12-31');
insert into INTERNS values(nextval('PUBLIC', 'INTERNS_SEQUENCE'), 'Dan Goia', 'dan.goia@accesa.eu', '2004-12-31');
insert into INTERNS values(nextval('PUBLIC', 'INTERNS_SEQUENCE'), 'Darius Has', 'darius.has@accesa.eu', '2004-12-31');
insert into INTERNS values(nextval('PUBLIC', 'INTERNS_SEQUENCE'), 'Doru Varga', 'doru.varga@accesa.eu', '2004-12-31');
insert into INTERNS values(nextval('PUBLIC', 'INTERNS_SEQUENCE'), 'Madalin Sava', 'madalin.sava@accesa.eu', '2004-12-31');
insert into INTERNS values(nextval('PUBLIC', 'INTERNS_SEQUENCE'), 'Marius Petrut', 'marius.petrut@accesa.eu', '2004-12-31');
insert into INTERNS values(nextval('PUBLIC', 'INTERNS_SEQUENCE'), 'Oana Pantea', 'oana.pantea@accesa.eu', '2004-12-31');
insert into INTERNS values(nextval('PUBLIC', 'INTERNS_SEQUENCE'), 'Raluca Gabor', 'raluca.gabor@accesa.eu', '2004-12-31');