CREATE TABLE IF NOT EXISTS INTERNS_HOBBIES (
 
    INTERN_ID int NOT NULL,
    HOBBY_ID int NOT NULL
);
 ALTER TABLE INTERNS_HOBBIES ADD FOREIGN KEY (INTERN_ID) REFERENCES INTERNS(ID);
 ALTER TABLE INTERNS_HOBBIES ADD FOREIGN KEY (HOBBY_ID) REFERENCES HOBBIES(ID);
