insert into HOBBIES values(nextval('PUBLIC', 'HOBBIES_SEQUENCE'), 'Fotbal');
insert into HOBBIES values(nextval('PUBLIC', 'HOBBIES_SEQUENCE'), 'Tenis');
insert into HOBBIES values(nextval('PUBLIC', 'HOBBIES_SEQUENCE'), 'Volei');
insert into HOBBIES values(nextval('PUBLIC', 'HOBBIES_SEQUENCE'), 'Ski');
insert into HOBBIES values(nextval('PUBLIC', 'HOBBIES_SEQUENCE'), 'Baschet');
insert into HOBBIES values(nextval('PUBLIC', 'HOBBIES_SEQUENCE'), 'Rugby');
insert into HOBBIES values(nextval('PUBLIC', 'HOBBIES_SEQUENCE'), 'Ping pong');
insert into HOBBIES values(nextval('PUBLIC', 'HOBBIES_SEQUENCE'), 'Biliard');
insert into INTERNS_HOBBIES values(1, 1);
insert into INTERNS_HOBBIES values(1, 7);
insert into INTERNS_HOBBIES values(2, 2);
insert into INTERNS_HOBBIES values(2, 8);
insert into INTERNS_HOBBIES values(3, 3);
insert into INTERNS_HOBBIES values(3, 1);
insert into INTERNS_HOBBIES values(4, 4);
insert into INTERNS_HOBBIES values(4, 6);
insert into INTERNS_HOBBIES values(5, 5);
insert into INTERNS_HOBBIES values(5, 8);
insert into INTERNS_HOBBIES values(6, 6);
insert into INTERNS_HOBBIES values(6, 3);
insert into INTERNS_HOBBIES values(7, 5);
insert into INTERNS_HOBBIES values(7, 8);
insert into INTERNS_HOBBIES values(8, 8);
insert into INTERNS_HOBBIES values(8, 1);
insert into INTERNS_HOBBIES values(9, 5);
insert into INTERNS_HOBBIES values(9, 8);
insert into INTERNS_HOBBIES values(10, 1);
insert into INTERNS_HOBBIES values(10, 2);
